ReRoutes: 
 - 
   DownstreamPathTemplate: "/api/values"
  DownstreamScheme: http
  DownstreamHostAndPorts: 
   - 
   Host: localhost
    Port: 7002
  UpstreamPathTemplate: "/account/{catchAll}"
 - 
   DownstreamPathTemplate: "/api/values"
  DownstreamScheme: http
  DownstreamHostAndPorts: 
   - 
   Host: localhost
    Port: 7001
  UpstreamPathTemplate: "/user/{catchAll}"
  UpstreamHttpMethod: 
GlobalConfiguration: 
 BaseUrl: "http://localhost:7000"
